language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: YcGolXQ6wBy2SAmjk0RE30DMiMQh16RHjNMGFfriE7TZvhtiUVdSBKCBEC2pvHzObXJud5qTpnP8tbLk1RqtTHMbDTuSRlCD4HwhYiDT7eFhMEPyU1J9mo5rpd0k31Mh1s286XQsxCZLN45Wq/hQ75tbYmBe+s3N8JD+HYmN79bDnwU7P9yLFO1F2nmE4WRKf3WGojEOGAcVLAhEqqx3lyIs6tjeC5Pkt1UmacKnzjDfX74dETMzOB6MvX/e5uB4nk3jrfhNMmquNnExLA1wZ/P7lTi2NTDuIORYxnGKRCUAX6xlPJPfvPDkSDaNRM7vzp2hucwF64ZdQJ+k0GfVg3LXhu/8fkrAp746TJpJV9FZiLnkEUL1ylx0TojRgD8N1mKgkIt9AO6Hrn4AIglpBCoPz5CIyUd0O3qmK5i9zK3W7CY1Aq7E1USPhWKot8YKvG7TYNa5iLxG8vDnse0Kp/LKUKOuNed/65f2Ol1V6l34IgvuuKKPX5TkrRk6+sdHbGjqHpfrKtJBRjthN2gfB8fkUbzfhaxYyMRfXcau8wC/QnUg2hXsV+rC4wKtA37tnEoHtp8mmZ1WAoClIsbB00+CMJzRQfkb/tuO3rPwGprktm6EW7tKrdgkBbJyuNluSNPkpBAWFCCsQm7jPKhB0gcpv3q+LrZcy41vfrHmROU=
  on: main
  app: bibliogoal
  skip_cleanup: true
