language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 83972c8d-11aa-470f-abd4-f24ac556b017
  on: main
  app: bibliogoal
  skip_cleanup: true
