language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: iR8j7xHKmCxqUKzVh1WhYCU2j0XzCW0nw+myzzfZNJKu8IP2Ifl/RgffcWhjdwyVj0ca/Fo0Vn9PBmqQCeIQCGuXx709gjxyhYNSFpmcW+jc9DhIAYU8HmBmBMKLQHxUUmnFvPvss/I5kYn8D9ogXX5dCU1zeHUuPv+HRdqjs3w6W09vXBtmjl1FOECcTov93k7ak3f7oOKZ9W3bs90D18EJ+TbxUZ4GFq4wh9LyyBZEDlTL5P7/X7D97yaGNauOPjyQUXezg8V4CRxnV0IpvXdlrJyTm8YWYqYC8garmYpqpyWw/lJRQQZKUD2gbiSvfrC4lUVdzv+n4kmXnjBl67f3aVjxuYmCJwgT1zxg5J6c37jALCQzVLtwJEhVodjBw4mMKYYZxGm1oOEynScVuAj4g8UNAw5/lS0l874bKF0ufa68dR4PDmEcii60I7wmh84R7ZnKyjo6k1nqALD2CWlvUu54arK61X4SzcJsUFh+p/zdm62QG8KIw8nL47qTGZeeNHYH+rH7sPKw+9va+SgUy+odeLV1w/C2EPqI5GK5+DKP2IR1xEY4BXnlY1CGbCL1RvqxoMDKbRnPKuLieVtFXaMxrkPvXXT3rD3DxPMOwJi8sW9Bf8NXtEBb8JCHURCwc8m54Ql8BhdtwSm1z58uLmcCpNf+FDUwmAxmTUA=
  on: main
  app: bibliogoal
  skip_cleanup: true
